name: Deployment Workflow
on:
  push:
    branches: [main]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('*package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: npm test

  deploy:
    name: Deploy
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master        
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ vars.PROJECT_PATH }}
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            git pull
            npm i 
            npm run build